name: Build and Publish
   on:
     push:
       branches:
         - master
   jobs:
     build:
       runs-on: ubuntu-latest
       steps:
         - name: Checkout repository
           uses: actions/checkout@v4
         
         - name: Set up JDK
           uses: actions/setup-java@v3
           with:
             distribution: 'temurin'
             java-version: '22'
         
         - name: Build with Gradle
           run: |
             chmod +x ./gradlew
             ./gradlew shadowJar --info
         
         - name: Debug - List all files in build directory
           run: |
             echo "Listing ALL files in build directory:"
             find build -type f
         
         - name: Find and copy JAR file
           run: |
             JAR_PATH=$(find build -name "*-all.jar" -o -name "*.jar" | grep -v "api" | head -n 1)
             if [ -z "$JAR_PATH" ]; then
               echo "No JAR file found!"
               exit 1
             fi
             echo "Found JAR file: $JAR_PATH"
             cp "$JAR_PATH" bot.jar
             ls -la bot.jar
         
         - name: Deploy jar to VPS
           uses: appleboy/scp-action@master
           with:
             host: ${{ secrets.HOST }}
             username: ${{ secrets.SSH_USER }}
             password: ${{ secrets.SSH_PASSWORD }}
             source: bot.jar
             target: /root
         
         - name: Deploy words.txt to VPS
           uses: appleboy/scp-action@master
           with:
             host: ${{ secrets.HOST }}
             username: ${{ secrets.SSH_USER }}
             password: ${{ secrets.SSH_PASSWORD }}
             source: words.txt
             target: /root

