name: Build and Publish

on:
  push:
    branches:
      - master # имя основной ветки

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew shadowJar

      - name: List build directory
        run: |
          echo "Listing all files in build directory:"
          find build -name "*.jar" -type f

      - name: Rename file
        run: mv build/libs/LearnWordTelegramBot-1.0-SNAPSHOT-all.jar bot.jar

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: bot-jar
          path: bot.jar

      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          source: "bot.jar"
          target: "/home/${{ secrets.USERNAME }}/bot"

      - name: Restart bot
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/${{ secrets.USERNAME }}/bot
            ./restart.sh
